### ISSUE TITLE
Fix URLs after Github organization renaming

### ISSUE THREAD

**Issue by spmaniato** [VerifiableRobotics/LTLMoPWeb3D#37]
URLs such as `https://github.com/LTLMoP/LTLMoPWeb3D.git` and `https://github.com/LTLMoP/LTLMoP.git` need to be renamed to account for the LTLMoP organization getting renamed to: https://github.com/VerifiableRobotics

**Comment by agilgur5** [comment]
Only references are in README and possibly Wiki, I'll get on this soon but it's been on the backburner because it doesn't affect any actual code.

**Comment by spmaniato** [comment]
OK. Last time I checked (before opening the issue), I remember seeing things like: `https://github.com/LTLMoP/LTLMoPWeb3D.git` in some configuration files and/or package manifests. I guess those aren't critical either.

**Comment by agilgur5** [comment]
@spmaniato you were correct, the NPM package manifest did have this (it's not a public package though, so that doesn't do anything right now anyway). Also interesting note, all the links in both the docs that I just pushed and in the wiki are now relative links - so they don't depend on the organization name at all (as this repo is under the same organization). This might be a useful tip for some of the other projects :)

**Comment by spmaniato** [comment]
> all the links in both the docs that I just pushed and in the wiki are now relative links - so they don't depend on the organization name at all (as this repo is under the same organization). This might be a useful tip for some of the other projects :)

Good idea, thanks!
